eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  address: 127.0.0.1
  port: 8763
  jsp-servlet:
    init-parameters:
      development: true
spring:
  data:
    solr:
      host: http://localhost:8080/solr/collection1
  application:
    name: server-member
  redis:
    host: localhost
    password: 123456
    port: 6379
    lettuce:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
  datasource:
      name: test
      url: jdbc:mysql://127.0.0.1:3306/springcloud-01
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  devtools:
    restart:
      enabled: true 
      additional-paths: src/main/java
      exclude: WEB-INF/pages/
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false   
messages:
   queue: messages_queue   
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.cn.common.domain
# 控制台sql打印
logging:
  level:
    org.springframework.web: debug
    com.cn.member.mapper: debug